require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false
